[project]
name = "yandex-polygon-parser"
version = "0.1.0"
description = "CLI to convert yandex polygon documentation to openapi spec."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
]
